### ISSUE TITLE
EFI não funciona no macOS Big Sur

### ISSUE THREAD

**Issue by OverlandAcorn09** [augustoperes1/Hackintosh-Essentials-E30-Open-Core#1]
Eu sei que no README está escrito que não havia testado com o Big Sur então foi exatamente por isso que testei.
Não sei se deveria postar isso aqui mas enfim, se quiser perguntar algo vou tentar ajudar!

**Comment by augustoperes1** [comment]
Pode me mandar uma foto da tela de boot verbose, bem como os logs que geraram na raiz do pendrive?

**Comment by OverlandAcorn09** [comment]
### Log
(obs: encontrei ele na partição EFI, acho que deve ser o log)
[opencore-2021-07-28-162740.txt](https://github.com/augustoperes1/Hackintosh-Essentials-E30-Open-Core/files/6895019/opencore-2021-07-28-162740.txt)

### Foto
Eu tirei a foto exatamente do momento em que começam os problemas e meio que entra em um loop

![20210728_133130](https://user-images.githubusercontent.com/85706899/127362109-4a098995-fff4-4a69-94ba-26a8acd8f352.jpg)

**Comment by OverlandAcorn09** [comment]
#### Eu dei uma checada no log que enviei e ele não abriu, talvez porque eu desliguei a força e isso de algum jeito corrompeu o aquivo? Enfim se não conseguir abrir com um editor de texto tente user o Vim ou Vi, se estiver no hackintosh ou em qualquer unix o Vi já está instalado é so executar pelo terminal:
    vi opencore-2021-07-28-162740.txt

**Comment by augustoperes1** [comment]
> #### Eu dei uma checada no log que enviei e ele não abriu, talvez porque eu desliguei a força e isso de algum jeito corrompeu o aquivo? Enfim se não conseguir abrir com um editor de texto tente user o Vim ou Vi, se estiver no hackintosh ou em qualquer unix o Vi já está instalado é so executar pelo terminal:
> ```
> vi opencore-2021-07-28-162740.txt
> ```

Abri no Kate e consegui visualizar tranquilamente. Obrigado pelo log. Tente essa EFI abaixo. Não esqueça de resetar a NVRAM.
[EFI.zip](https://github.com/augustoperes1/Hackintosh-Essentials-E30-Open-Core/files/6910431/EFI.zip)
Coloque a sua SMBIOS nessa EFI

**Comment by augustoperes1** [comment]
@OverlandAcorn09 Funcionou?

**Comment by OverlandAcorn09** [comment]
> @OverlandAcorn09 Funcionou?

Eu ainda não tive tempo de testar mas assim que puder eu tento e vejo se funciona

**Comment by augustoperes1** [comment]
@OverlandAcorn09 Testou?

**Comment by OverlandAcorn09** [comment]
> @OverlandAcorn09 Testou?

Opa foi mal. Tinha esquecido de responder, aconteceu que caiu no mesmo problema.. Acho que o hardware é incompatível mesmo :(

Mas muito obrigado pela ajuda de qualquer maneira se quiser posso enviar o log depois

**Comment by augustoperes1** [comment]
> > @OverlandAcorn09 Testou?
> 
> Opa foi mal. Tinha esquecido de responder, aconteceu que caiu no mesmo problema.. Acho que o hardware é incompatível mesmo :(
> 
> Mas muito obrigado pela ajuda de qualquer maneira se quiser posso enviar o log depois

Manda foto da tela e log, por favor
